source ~/.zsh/aliases.zsh
source ~/.zsh/functions.zsh
source ~/.zsh/vars.zsh
source ~/.zsh/settings.zsh
source ~/.zsh/colors.zsh
source ~/.zsh/bindkeys.zsh
source ~/.zsh/completion.zsh
source ~/.zsh/exports.zsh
source ~/.zsh/history.zsh
. ~/github/powerline/powerline/bindings/zsh/powerline.zsh
